baseURL = "http://shubhsharma.net/"
languageCode = "en-us"
title = "Shubh Sharma"
theme = "minimal"

[params]
    author = "Shubh Sharma"
    description = "I am Shubh Sharma a Computer Science Engineering undergraduate student at the HMR Institute of Technology and Management, Guru Gobind Singh Indraprastha University. Check out the About section to know more about me and my hobbies."
    accent = "Orange"
    showBorder = true
    backgroundColor = "White"
    font = "Raleway"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

#SOCIAL ICONS

[[menu.icon]]
    url = "flummoxedshubh@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/flummoxedShubh/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/flummoxedShubh/"
    name = "twitter"
    weight = 3

